//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catalogoMobileAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecARTICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ecARTICULO()
        {
            this.ecCARRITO = new HashSet<ecCARRITO>();
            this.ecCOMENTARIO = new HashSet<ecCOMENTARIO>();
            this.ecFAVORITO = new HashSet<ecFAVORITO>();
            this.ecIMAGEN = new HashSet<ecIMAGEN>();
        }
    
        public string idArticulo { get; set; }
        public int idEmpresa { get; set; }
        public string idCategoria { get; set; }
        public string idMarca { get; set; }
        public string numCatalogo { get; set; }
        public string estatus { get; set; }
        public string nomArticulo { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public string tipo { get; set; }
        public string idUnidad { get; set; }
        public Nullable<int> visitas { get; set; }
        public Nullable<System.DateTime> fechaUltimaVisita { get; set; }
        public Nullable<int> ctdCompartido { get; set; }
        public System.DateTime fecha { get; set; }
        public string idUsuario { get; set; }
        public int indice { get; set; }
        public string estrella { get; set; }
        public string rebaja { get; set; }
        public string relevancia { get; set; }
        public string promo { get; set; }
    
        public virtual ecCATEGORIA ecCATEGORIA { get; set; }
        public virtual ecEMPRESA ecEMPRESA { get; set; }
        public virtual ecMARCA ecMARCA { get; set; }
        public virtual ecUNIDAD ecUNIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecCARRITO> ecCARRITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecCOMENTARIO> ecCOMENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecFAVORITO> ecFAVORITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecIMAGEN> ecIMAGEN { get; set; }
    }
}
