//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catalogoMobileAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecCARRITO
    {
        public int idCarrito { get; set; }
        public int idEmpresa { get; set; }
        public int idPedido { get; set; }
        public string idArticulo { get; set; }
        public decimal precio { get; set; }
        public decimal cantidad { get; set; }
        public decimal importe { get; set; }
    
        public virtual ecARTICULO ecARTICULO { get; set; }
        public virtual ecPEDIDO ecPEDIDO { get; set; }
    }
}
