//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catalogoMobileAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecEMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ecEMPRESA()
        {
            this.ecARTICULO = new HashSet<ecARTICULO>();
            this.ecCATEGORIA = new HashSet<ecCATEGORIA>();
            this.ecMARCA = new HashSet<ecMARCA>();
            this.ecPERFIL = new HashSet<ecPERFIL>();
            this.ecSUCURSAL = new HashSet<ecSUCURSAL>();
        }
    
        public int idEmpresa { get; set; }
        public string SKU { get; set; }
        public string razonsocial { get; set; }
        public string rfc { get; set; }
        public string direccion { get; set; }
        public string delegacion { get; set; }
        public string ciudad { get; set; }
        public string estado { get; set; }
        public string pais { get; set; }
        public string nomContacto { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string nomBanco { get; set; }
        public string numTarjeta { get; set; }
        public string clabe { get; set; }
        public string urlTinda { get; set; }
        public string urlSitioWeb { get; set; }
        public string urlFaceBook { get; set; }
        public string urlYouTube { get; set; }
        public string urlInstagram { get; set; }
        public string urlTwitter { get; set; }
        public System.DateTime fecha { get; set; }
        public string estatus { get; set; }
        public int visitas { get; set; }
        public Nullable<System.DateTime> fechaUtimaVisita { get; set; }
        public string descNegocio { get; set; }
        public string urlImagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecARTICULO> ecARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecCATEGORIA> ecCATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecMARCA> ecMARCA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecPERFIL> ecPERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecSUCURSAL> ecSUCURSAL { get; set; }
    }
}
