//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catalogoMobileAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecPEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ecPEDIDO()
        {
            this.ecCARRITO = new HashSet<ecCARRITO>();
        }
    
        public int idPedido { get; set; }
        public int idEmpresa { get; set; }
        public string idUsuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string notas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecCARRITO> ecCARRITO { get; set; }
        public virtual ecUSUARIO ecUSUARIO { get; set; }
    }
}
