//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catalogoMobileAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecPERFIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ecPERFIL()
        {
            this.ecPERFILDET = new HashSet<ecPERFILDET>();
            this.ecUSUARIO = new HashSet<ecUSUARIO>();
        }
    
        public string idPerfil { get; set; }
        public int idEmpresa { get; set; }
        public string nomPerfil { get; set; }
        public string estatus { get; set; }
    
        public virtual ecEMPRESA ecEMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecPERFILDET> ecPERFILDET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecUSUARIO> ecUSUARIO { get; set; }
    }
}
