//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catalogoMobileAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecPERFILDET
    {
        public int idPerfilDet { get; set; }
        public string idPerfil { get; set; }
        public int idEmpresa { get; set; }
        public string idMenu { get; set; }
    
        public virtual ecMENU ecMENU { get; set; }
        public virtual ecPERFIL ecPERFIL { get; set; }
    }
}
