//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace catalogoMobileAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecUSUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ecUSUARIO()
        {
            this.ecPEDIDO = new HashSet<ecPEDIDO>();
            this.ecCOMENTARIO = new HashSet<ecCOMENTARIO>();
            this.ecFAVORITO = new HashSet<ecFAVORITO>();
        }
    
        public string idUsuario { get; set; }
        public int idEmpresa { get; set; }
        public string idSucursal { get; set; }
        public string idPerfil { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public Nullable<int> mesCumple { get; set; }
        public Nullable<int> diaCumple { get; set; }
        public string genero { get; set; }
        public System.DateTime fecha { get; set; }
        public string estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecPEDIDO> ecPEDIDO { get; set; }
        public virtual ecPERFIL ecPERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecCOMENTARIO> ecCOMENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecFAVORITO> ecFAVORITO { get; set; }
    }
}
